% Read data from files generated by HList
% Author: Xiao Xiong
% Date Created: 25 Jan 2005
% Date Lasted modefied: 25 Jan 2005

function [data] = readSPH(file_name);

% read in the log Mel vectors first
FILE = fopen( file_name );
tmp = textscan(FILE,'%s',1);
NIST_label = tmp{1};
% get the header size
tmp = textscan(FILE,'%s',1);
Header_size = str2num(tmp{1}{1});
% get the sampling rate
tmp = textscan(FILE,'%s',2);
sr_label = tmp{1};
tmp = textscan(FILE,'%s',1);
sr = str2num(tmp{1}{1});
% get the sample size
tmp = textscan(FILE,'%s',2);
samp_size_label = tmp{1};
tmp = textscan(FILE,'%s',1);
samp_size = str2num(tmp{1}{1});
% get the channel output
tmp = textscan(FILE,'%s',2);
ch_out_label = tmp{1};
tmp = textscan(FILE,'%s',1);
ch_out = str2num(tmp{1}{1});
% get the sample count
tmp = textscan(FILE,'%s',2);
samp_count_label = tmp{1};
tmp = textscan(FILE,'%s',1);
samp_count = str2num(tmp{1}{1});
% rewind to the beginning of the file
frewind(FILE);
% read all the header
fread(FILE, Header_size, 'int16')';
% read the data
data = fread(FILE,min(10^7,samp_count),'int16','ieee-be');

fclose(FILE);