% Read data from files generated by HList
% Author: Xiao Xiong
% Date Created: 25 Jan 2005
% Date Lasted modefied: 25 Jan 2005

function [data] = readHTK(file_name, vector_size, big_endian, dimFirst)

% read in the log Mel vectors first
FILE = fopen( file_name );
if nargin<4
    dimFirst = 0;
end
if nargin < 3
    endian = 'ieee-le';
elseif big_endian == 1
    endian = 'ieee-be';
else
    endian = 'ieee-le';
end

if nargin<2
    vector_size = [];
end

N_vector = fread(FILE, 1, 'int32=>uint32', endian);
sampPeriod = fread(FILE, 1, 'int32', endian);   % in unit of 
sampSize = fread(FILE, 1, 'int16', endian); % number of bytes per sample
parmKind = fread(FILE, 1, 'int16', endian);

if length(vector_size)==0
    vector_size = sampSize / 4;
end

% Faster implementation
N_element = double(N_vector) * vector_size;
if 0
    temp = fread(FILE, N_element, 'float32', endian);
    if length(temp) ~= N_element
        fprintf('Corrupted file: %s\n', file_name);
    end
    data = reshape(temp,vector_size,N_vector);
else
    data = fread(FILE, [vector_size N_vector], 'float32', endian);
end
if dimFirst==0
    data = data';
end
% data = zeros(N_vector,vector_size);
% for i=1:N_vector
%     temp = fread(FILE, vector_size, 'float32', endian)';
%     data(i,:) = temp;
% end
fclose(FILE);