% Read data from files generated by HList
% Author: Xiao Xiong
% Date Created: 25 Jan 2005
% Date Lasted modefied: 25 Jan 2005

function x = readHList(file_name, vector_size);

    % read in the log Mel vectors first
    FILE = fopen( file_name );
    j=0;
    fsearch(':', FILE);     % skip the first ':'
    while fsearch(':', FILE) == 0   % read N_spectral number immediately after ':'
        j = j+1;
        temp = textscan(FILE, '%n', vector_size);
        x(:,j) = temp{1};        % store the vecors as column vector of logmel
    end
    num_of_vector_in_current_file = j;
    
