%
% Read the alignment file generated by HTK
%

function [utt_name, label] = readMLF(file_name, option)

FID = fopen(file_name, 'r');
fgetl(FID);

utt_cnt = 0;
for i=1:10^8
    if mod(i,10000)==0, fprintf('%d lines processed\n', i); end
    temp = fgetl(FID);
    if temp == -1
        break;
    elseif temp(1) == '#'
        continue;
    elseif ~isempty(regexp(temp,'.rec"','ONCE')) || ~isempty(regexp(temp,'.lab"','ONCE'))
        utt_cnt = utt_cnt + 1;
        utt_name{utt_cnt} = temp(4:end-5);
        label{utt_cnt} = {};
    elseif strcmp(temp, '.')==0
        label{utt_cnt}{end+1} = temp;
    end
end
fclose(FID);
